name: dart_webrtc
description: Use the dart/js library to re-wrap the webrtc js interface of the browser, to adapted common browsers.
version: 0.2.3
homepage: https://github.com/flutter-webrtc/dart-webrtc

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  js: ^0.6.2
#  path: ^1.7.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
  protoo_client: ^0.3.0
  http: any
  test: ^1.15.4